apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: github-ca-v2
  namespace: fleet-default
spec:
  branch: main
  insecureSkipTLSVerify: false
  paths:
  - /application
  repo: https://github.com/MagicManolo/demo.git
  targets:
  - clusterSelector:
      matchExpressions:
      - key: provider.cattle.io
        operator: NotIn
        values:
        - harvester
